spring.application.name=Biblioteca

spring.datasource.url=jdbc:oracle:thin:@//192.168.0.200:1522/UNIFIL
spring.datasource.username=unifil
spring.datasource.password=unifil
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create
jwt.secret="UjCH|lm#-m(N.,z;aj$w^yOwJPF3oL6a52EW8=&P:@=d%D?f+#j4Ode3zx3>%EJ3kqZ)F](O,A7GQPBz_gp[1|L6]UPHX.J+p06,2q20;Sw*c|WZlL&^zpca&$;vz|C*wG!uNUL:BOyISeL2o#v&7?]hdSgzvSf0-:OI*(L*+:,SJq86ZU)&oDbX]S{^nYfDsd&]yl.T"